version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ecommerce_bd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: stiv
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: ecommerce_mongo_bd

  app:
    build: .
    container_name: technical-test-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://stiv:123456@mongodb:27017/ecommerce_mongo_bd?authSource=admin
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/ecommerce_bd
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: root
    depends_on:
      - postgres
      - mongodb